# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7729962d6e74c2428cef36026ae2487e184edf98a7c248aff2d8a4231f90eabfb9c6d972e10c2800145ebd1540cc06948099107b34e6a0b5e876acbc33061fe2

test:
  secret_key_base: f6b29be767dd0f71e974095d0211af0b7f1bfa57749c299ec567fcb3293a13973b9aa91e526bc3d3d9d3b08d980971840bde27020486c555e9dff12d3e16713b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
